In [2]:
import numpy as np 
import pandas as pd

In [16]:
df1 = pd.read_csv('C:/Users/ASUS/bikeshare2018/bikeshare2018/Bike Share Toronto Ridership_Q1 2018.csv')
q1_2018 = df1.copy()

In [17]:
route_station = np.where(q1_2018['from_station_id'] == q1_2018['to_station_id'], 'Init point', 'different point')
route_station

array(['different point', 'different point', 'different point', ...,
       'different point', 'different point', 'different point'],
      dtype='<U15')

In [18]:
q1_2018['Return point'] = route_station

In [19]:
q1_2018

,trip_id,trip_duration_seconds,from_station_id,trip_start_time,from_station_name,trip_stop_time,to_station_id,to_station_name,user_type,Return point
0,2383648,393,7018,1/1/2018 0:47,Bremner Blvd / Rees St,1/1/2018 0:54,7176,Bathurst St / Fort York Blvd,Annual Member,different point
1,2383649,625,7184,1/1/2018 0:52,Ossington Ave / College St,1/1/2018 1:03,7191,Central Tech (Harbord St),Annual Member,different point
2,2383650,233,7235,1/1/2018 0:55,Bay St / College St (West Side) - SMART,1/1/2018 0:59,7021,Bay St / Albert St,Annual Member,different point
3,2383651,1138,7202,1/1/2018 0:57,Queen St W / York St (City Hall),1/1/2018 1:16,7020,Phoebe St / Spadina Ave,Annual Member,different point
4,2383652,703,7004,1/1/2018 1:00,University Ave / Elm St,1/1/2018 1:12,7060,Princess St / Adelaide St E,Annual Member,different point
...,...,...,...,...,...,...,...,...,...,...
178554,2605019,746,7017,3/31/2018 23:48,Widmer St / Adelaide St W,4/1/2018 0:00,7006,Bay St / College St (East Side),Annual Member,different point
178555,2605020,803,7009,3/31/2018 23:51,King St E / Jarvis St,4/1/2018 0:05,7114,Carlton St / Parliament St,Annual Member,different point
178556,2605021,411,7062,3/31/2018 23:54,University Ave / College St (West),4/1/2018 0:00,7051,Wellesley St E / Yonge St (Green P),Annual Member,different point
178557,2605022,164,7002,3/31/2018 23:54,St. George St / Bloor St W,3/31/2018 23:57,7250,St. George St / Russell St - SMART,Annual Member,different point
178558,2605023,1134,7029,3/31/2018 23:55,St. James Park (King St. E.),4/1/2018 0:14,7076,York St / Queens Quay W,Annual Member,different point

In [20]:
return_point = q1_2018['Return point'].value_counts() 
return_point

different point    176260
Init point           2299
Name: Return point, dtype: int64

In [36]:
All_bike = q1_2018['Return point'].count()
Init_bike = return_point['Init point']
bike_returned = (Init_bike/All_bike)*100
print('Percentage of Q1 2018 is %.2f' %bike_returned, '%' )

Percentage of Q1 2018 is 1.29 %

In [61]:
df1 = pd.read_csv('C:/Users/ASUS/bikeshare2018/bikeshare2018/Bike Share Toronto Ridership_Q1 2018.csv')
q1_2018 = df1.copy()
df2 = pd.read_csv('C:/Users/ASUS/bikeshare2018/bikeshare2018/Bike Share Toronto Ridership_Q2 2018.csv')
q2_2018 = df2.copy()
df3 = pd.read_csv('C:/Users/ASUS/bikeshare2018/bikeshare2018/Bike Share Toronto Ridership_Q3 2018.csv')
q3_2018 = df3.copy()
df4 = pd.read_csv('C:/Users/ASUS/bikeshare2018/bikeshare2018/Bike Share Toronto Ridership_Q4 2018.csv')
q4_2018 = df4.copy()

In [62]:
route_station1 = np.where(q1_2018['from_station_id'] == q1_2018['to_station_id'], 'Init point', 'different point')
route_station2 = np.where(q2_2018['from_station_id'] == q2_2018['to_station_id'], 'Init point', 'different point')
route_station3 = np.where(q3_2018['from_station_id'] == q3_2018['to_station_id'], 'Init point', 'different point')
route_station4 = np.where(q4_2018['from_station_id'] == q4_2018['to_station_id'], 'Init point', 'different point')

In [63]:
q1_2018['Return point'] = route_station1
q2_2018['Return point'] = route_station2
q3_2018['Return point'] = route_station3
q4_2018['Return point'] = route_station4

In [64]:
q1_2018

,trip_id,trip_duration_seconds,from_station_id,trip_start_time,from_station_name,trip_stop_time,to_station_id,to_station_name,user_type,Return point
0,2383648,393,7018,1/1/2018 0:47,Bremner Blvd / Rees St,1/1/2018 0:54,7176,Bathurst St / Fort York Blvd,Annual Member,different point
1,2383649,625,7184,1/1/2018 0:52,Ossington Ave / College St,1/1/2018 1:03,7191,Central Tech (Harbord St),Annual Member,different point
2,2383650,233,7235,1/1/2018 0:55,Bay St / College St (West Side) - SMART,1/1/2018 0:59,7021,Bay St / Albert St,Annual Member,different point
3,2383651,1138,7202,1/1/2018 0:57,Queen St W / York St (City Hall),1/1/2018 1:16,7020,Phoebe St / Spadina Ave,Annual Member,different point
4,2383652,703,7004,1/1/2018 1:00,University Ave / Elm St,1/1/2018 1:12,7060,Princess St / Adelaide St E,Annual Member,different point
...,...,...,...,...,...,...,...,...,...,...
178554,2605019,746,7017,3/31/2018 23:48,Widmer St / Adelaide St W,4/1/2018 0:00,7006,Bay St / College St (East Side),Annual Member,different point
178555,2605020,803,7009,3/31/2018 23:51,King St E / Jarvis St,4/1/2018 0:05,7114,Carlton St / Parliament St,Annual Member,different point
178556,2605021,411,7062,3/31/2018 23:54,University Ave / College St (West),4/1/2018 0:00,7051,Wellesley St E / Yonge St (Green P),Annual Member,different point
178557,2605022,164,7002,3/31/2018 23:54,St. George St / Bloor St W,3/31/2018 23:57,7250,St. George St / Russell St - SMART,Annual Member,different point
178558,2605023,1134,7029,3/31/2018 23:55,St. James Park (King St. E.),4/1/2018 0:14,7076,York St / Queens Quay W,Annual Member,different point

In [65]:
q2_2018

,trip_id,trip_duration_seconds,from_station_id,trip_start_time,from_station_name,trip_stop_time,to_station_id,to_station_name,user_type,Return point
0,2605025,1666,7000,4/1/2018 0:01,Fort York Blvd / Capreol Ct,4/1/2018 0:29,7150,Dufferin St / Sylvan Av (Dufferin Grove Park),Annual Member,different point
1,2605024,247,7051,4/1/2018 0:01,Wellesley St E / Yonge St (Green P),4/1/2018 0:05,7042,Sherbourne St / Wellesley St E,Annual Member,different point
2,2605026,2032,7062,4/1/2018 0:03,University Ave / College St (West),4/1/2018 0:37,7056,Parliament St / Gerrard St,Annual Member,different point
3,2605027,531,7063,4/1/2018 0:03,Queen's Park / Bloor St W,4/1/2018 0:12,7143,Kendal Ave / Bernard Ave,Annual Member,different point
4,2605028,642,7199,4/1/2018 0:05,College St / Markham St,4/1/2018 0:15,7004,University Ave / Elm St,Annual Member,different point
...,...,...,...,...,...,...,...,...,...,...
558365,3244394,7224,7317,6/30/2018 23:58,Hubbard Blvd / Balsam Av,7/1/2018 1:59,7317,Hubbard Blvd / Balsam Av,Casual Member,Init point
558366,3244392,1560,7107,6/30/2018 23:58,Cherry St / Distillery Ln,7/1/2018 0:24,7010,King St W / Spadina Ave,Annual Member,different point
558367,3244393,1144,7152,6/30/2018 23:58,Ossington Ave / Bloor St W,7/1/2018 0:17,7126,Yonge St / Yorkville Ave,Annual Member,different point
558368,3244391,248,7235,6/30/2018 23:58,Bay St / College St (West Side) - SMART,7/1/2018 0:02,7026,Bay St / St. Joseph St,Annual Member,different point
558369,3244395,1075,7107,6/30/2018 23:59,Cherry St / Distillery Ln,7/1/2018 0:16,7075,Queens Quay W / Dan Leckie Way,Annual Member,different point

In [3]:
return_point_concat= pd.concat([q1_2018, q2_2018, q3_2018, q4_2018])
return_point_concat

NameError: name 'q1_2018' is not defined